package com.bearfamily.app.bearontime.dev;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

public final class VoiceBackupBridge {
    static final int REQ_EXPORT_ONE=1910, REQ_EXPORT_ALL=1911, REQ_IMPORT_ALL=1912;
    private static final long MAX_BYTES=300L*1024L*1024L; private static final int MAX_ENTRIES=1200;
    private final Activity activity; private final WebView webView; private String pendingModuleId="", pendingSelectedId="bear_default";
    VoiceBackupBridge(Activity a,WebView w){activity=a;webView=w;}
    @JavascriptInterface public boolean isAvailable(){return true;}
    @JavascriptInterface public void exportVoiceModule(final String moduleId,final String displayName){if(moduleId==null||moduleId.trim().isEmpty()||"bear_default".equals(moduleId)){notifyResult(false,"export_one",0,"內建語音不需要匯出；APK 本身已包含。","");return;}activity.runOnUiThread(new Runnable(){public void run(){try{File d=moduleDir(moduleId);if(!d.isDirectory())throw new Exception("找不到語音模組");pendingModuleId=moduleId;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,fileSafe(safeName(displayName,readModuleName(d)))+".zip");activity.startActivityForResult(i,REQ_EXPORT_ONE);}catch(Throwable t){notifyResult(false,"export_one",0,msg(t),"");}}});}
    @JavascriptInterface public void exportAllVoiceModules(final String selectedId){activity.runOnUiThread(new Runnable(){public void run(){try{pendingSelectedId=selectedId==null?"bear_default":selectedId;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"熊正點報時_語音模組完整備份.zip");activity.startActivityForResult(i,REQ_EXPORT_ALL);}catch(Throwable t){notifyResult(false,"export_all",0,msg(t),"");}}});}
    @JavascriptInterface public void importVoiceBackup(){activity.runOnUiThread(new Runnable(){public void run(){try{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/zip","application/x-zip-compressed","application/octet-stream"});activity.startActivityForResult(i,REQ_IMPORT_ALL);}catch(Throwable t){notifyResult(false,"import_all",0,msg(t),"");}}});}
    boolean handleActivityResult(int requestCode,int resultCode,Intent data){if(requestCode!=REQ_EXPORT_ONE&&requestCode!=REQ_EXPORT_ALL&&requestCode!=REQ_IMPORT_ALL)return false;if(resultCode!=Activity.RESULT_OK||data==null||data.getData()==null)return true;final Uri uri=data.getData();final int req=requestCode;new Thread(new Runnable(){public void run(){if(req==REQ_EXPORT_ONE)exportOneTo(uri);else if(req==REQ_EXPORT_ALL)exportAllTo(uri);else importAllFrom(uri);}},"BearVoiceBackup").start();return true;}
    private void exportOneTo(Uri uri){try{File d=moduleDir(pendingModuleId);if(!d.isDirectory())throw new Exception("找不到語音模組");String name=readModuleName(d);OutputStream raw=activity.getContentResolver().openOutputStream(uri,"w");if(raw==null)throw new Exception("無法建立備份 ZIP");ZipOutputStream z=new ZipOutputStream(new BufferedOutputStream(raw));try{JSONObject m=new JSONObject();m.put("format","BearOnTime-Voice-Module");m.put("version",1);m.put("name",name);putText(z,"manifest.json",m.toString(2));File[] fs=d.listFiles();if(fs!=null)for(File f:fs){if(f==null||!f.isFile()||"name.txt".equalsIgnoreCase(f.getName()))continue;putFile(z,f,f.getName());}}finally{try{z.finish();}catch(Throwable ignored){}try{z.close();}catch(Throwable ignored){}}notifyResult(true,"export_one",1,"語音模組已匯出："+name,"");}catch(Throwable t){notifyResult(false,"export_one",0,msg(t),"");}}
    private void exportAllTo(Uri uri){try{File[] dirs=modulesRoot().listFiles();JSONArray mods=new JSONArray();int count=0;OutputStream raw=activity.getContentResolver().openOutputStream(uri,"w");if(raw==null)throw new Exception("無法建立完整備份 ZIP");ZipOutputStream z=new ZipOutputStream(new BufferedOutputStream(raw));try{if(dirs!=null)for(File d:dirs){if(d==null||!d.isDirectory()||d.getName().startsWith("."))continue;JSONObject mo=new JSONObject();mo.put("id",d.getName());mo.put("name",readModuleName(d));mods.put(mo);String base="modules/"+d.getName()+"/";putText(z,base+"name.txt",readModuleName(d));File[] fs=d.listFiles();if(fs!=null)for(File f:fs){if(f==null||!f.isFile()||"name.txt".equalsIgnoreCase(f.getName()))continue;putFile(z,f,base+f.getName());}count++;}JSONObject bundle=new JSONObject();bundle.put("format","BearOnTime-Voice-Backup");bundle.put("version",1);bundle.put("selected",pendingSelectedId==null?"bear_default":pendingSelectedId);bundle.put("modules",mods);putText(z,"bear_voice_bundle.json",bundle.toString(2));}finally{try{z.finish();}catch(Throwable ignored){}try{z.close();}catch(Throwable ignored){}}notifyResult(true,"export_all",count,count==0?"目前沒有自訂語音；已建立空白備份。":"已備份 "+count+" 組自訂語音。",pendingSelectedId);}catch(Throwable t){notifyResult(false,"export_all",0,msg(t),"");}}
    private void importAllFrom(Uri uri){File temp=new File(activity.getCacheDir(),"voice_restore_"+System.currentTimeMillis());try{if(!temp.mkdirs()&&!temp.isDirectory())throw new Exception("無法建立還原暫存區");InputStream raw=activity.getContentResolver().openInputStream(uri);if(raw==null)throw new Exception("無法開啟語音備份 ZIP");ZipInputStream zin=new ZipInputStream(new BufferedInputStream(raw));long total=0;int entries=0;try{ZipEntry e;byte[] buf=new byte[8192];while((e=zin.getNextEntry())!=null){if(++entries>MAX_ENTRIES)throw new Exception("備份 ZIP 項目過多");if(e.isDirectory()){zin.closeEntry();continue;}String name=normalizeEntry(e.getName());if(name.isEmpty()){zin.closeEntry();continue;}File out=new File(temp,name);String root=temp.getCanonicalPath()+File.separator;if(!out.getCanonicalPath().startsWith(root))throw new Exception("ZIP 路徑不安全");File p=out.getParentFile();if(p!=null&&!p.exists())p.mkdirs();FileOutputStream fos=new FileOutputStream(out,false);try{int n;while((n=zin.read(buf))>0){total+=n;if(total>MAX_BYTES)throw new Exception("語音備份容量超過限制");fos.write(buf,0,n);}fos.flush();}finally{try{fos.close();}catch(Throwable ignored){}}zin.closeEntry();}}finally{try{zin.close();}catch(Throwable ignored){}try{raw.close();}catch(Throwable ignored){}}File mf=new File(temp,"bear_voice_bundle.json");if(!mf.isFile())throw new Exception("這不是熊正點報時的完整語音備份。單一語音 ZIP 請使用『匯入語音 ZIP』。");JSONObject bundle=new JSONObject(readText(mf));if(!"BearOnTime-Voice-Backup".equals(bundle.optString("format")))throw new Exception("語音備份格式不相容");JSONArray mods=bundle.optJSONArray("modules");String selected=bundle.optString("selected","bear_default");Map<String,String> map=new HashMap<String,String>();int restored=0;if(mods!=null)for(int i=0;i<mods.length();i++){JSONObject mo=mods.optJSONObject(i);if(mo==null)continue;String oldId=cleanId(mo.optString("id",""));if(oldId.isEmpty())continue;File src=new File(new File(temp,"modules"),oldId);if(!src.isDirectory())continue;String newId=uniqueId(oldId);File dst=new File(modulesRoot(),newId);if(!dst.mkdirs()&&!dst.isDirectory())continue;copyModule(src,dst);writeText(new File(dst,"name.txt"),safeName(mo.optString("name",""),readModuleName(src)));map.put(oldId,newId);restored++;}String sel=map.containsKey(selected)?map.get(selected):"bear_default";notifyResult(true,"import_all",restored,restored==0?"備份內沒有自訂語音。":"已還原 "+restored+" 組自訂語音。",sel);}catch(Throwable t){notifyResult(false,"import_all",0,msg(t),"");}finally{deleteRecursive(temp);}}
    private void notifyResult(boolean ok,String action,int count,String message,String selected){try{JSONObject o=new JSONObject();o.put("ok",ok);o.put("action",action);o.put("count",count);o.put("message",message);o.put("selected",selected==null?"":selected);final String js="window.__bearVoiceBackupDone&&window.__bearVoiceBackupDone("+o.toString()+")";webView.post(new Runnable(){public void run(){try{webView.evaluateJavascript(js,null);}catch(Throwable ignored){}}});}catch(Throwable ignored){}}
    private File modulesRoot(){File r=new File(activity.getFilesDir(),"voice_modules");if(!r.exists())r.mkdirs();return r;}private File moduleDir(String id){return new File(modulesRoot(),cleanId(id));}private static String cleanId(String id){return id==null?"":id.replaceAll("[^A-Za-z0-9_-]","");}
    private String uniqueId(String base){String b=cleanId(base);if(b.isEmpty())b="voice_restore";if(!new File(modulesRoot(),b).exists())return b;long now=System.currentTimeMillis();for(int i=0;i<100;i++){String n=b+"_r"+now+(i==0?"":"_"+i);if(!new File(modulesRoot(),n).exists())return n;}return "voice_restore_"+now;}
    private static void copyModule(File src,File dst)throws Exception{File[] fs=src.listFiles();if(fs==null)return;byte[] buf=new byte[8192];for(File f:fs){if(f==null||!f.isFile())continue;String n=f.getName();if(!("name.txt".equalsIgnoreCase(n)||isAudioName(n)))continue;FileInputStream in=new FileInputStream(f);FileOutputStream out=new FileOutputStream(new File(dst,n),false);try{int c;while((c=in.read(buf))>0)out.write(buf,0,c);out.flush();}finally{try{in.close();}catch(Throwable ignored){}try{out.close();}catch(Throwable ignored){}}}}
    private static boolean isAudioName(String n){String l=n==null?"":n.toLowerCase(Locale.US);return l.endsWith(".mp3")||l.endsWith(".wav")||l.endsWith(".ogg")||l.endsWith(".m4a")||l.endsWith(".aac");}
    private static String normalizeEntry(String n){if(n==null)return "";String s=n.replace('\\','/');while(s.startsWith("/"))s=s.substring(1);if(s.contains("../")||s.equals(".."))return "";return s;}
    private static void putText(ZipOutputStream z,String name,String text)throws Exception{z.putNextEntry(new ZipEntry(name));byte[] b=(text==null?"":text).getBytes(StandardCharsets.UTF_8);z.write(b);z.closeEntry();}
    private static void putFile(ZipOutputStream z,File f,String name)throws Exception{z.putNextEntry(new ZipEntry(name));FileInputStream in=new FileInputStream(f);byte[] b=new byte[8192];try{int n;while((n=in.read(b))>0)z.write(b,0,n);}finally{try{in.close();}catch(Throwable ignored){}}z.closeEntry();}
    private static String readText(File f)throws Exception{FileReader r=new FileReader(f);StringBuilder s=new StringBuilder();char[] b=new char[2048];try{int n;while((n=r.read(b))>0)s.append(b,0,n);}finally{try{r.close();}catch(Throwable ignored){}}return s.toString();}
    private static void writeText(File f,String text)throws Exception{FileWriter w=new FileWriter(f,false);try{w.write(text==null?"":text);}finally{try{w.close();}catch(Throwable ignored){}}}
    private static String readModuleName(File d){File f=new File(d,"name.txt");if(!f.isFile())return d.getName();try{return safeName(readText(f),d.getName());}catch(Throwable t){return d.getName();}}
    private static String safeName(String s,String fallback){String v=s==null?"":s.trim().replaceAll("[\\r\\n\\t]+"," ");if(v.isEmpty())v=fallback==null?"自訂語音":fallback;return v.length()>40?v.substring(0,40):v;}
    private static String fileSafe(String s){String v=safeName(s,"熊正點報時語音").replaceAll("[\\\\/:*?\"<>|]+","_");return v.isEmpty()?"熊正點報時語音":v;}
    private static boolean deleteRecursive(File f){if(f==null||!f.exists())return true;if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File c:a)deleteRecursive(c);}return f.delete();}
    private static String msg(Throwable t){String m=t==null?"":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}
}
